### ISSUE TITLE
Failing Test Case - FAILED tests/test_transcription_decorator.py::test_transcription_processing_success[tests/resources/test_files/Taylor Swift.mp4]

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#120]
FAILED tests/test_transcription_decorator.py::test_transcription_processing_success[tests/resources/test_files/Taylor Swift.mp4]

Suspect that the test is failing due to inconsistency in the model. Perhaps this test case should be changed to check for a common phrase in the audio file?

**Comment by benjaminLuoHC** [comment]
The test is currently passing after the Nov. 30 change that implemented Cosine similarity with the passing criteria of 80% (the Taylor Swift file scores around the high 80s +/- 6%)
