### ISSUE TITLE
Test Cases Modify files

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#121]
The test cases modify the following files. Although that is OK, a step should be added to the test teardown to revert these files so that there is change to the files after the test finishes.

This is currently resulting in git wanting to commit changes to these test files:

- HealthCanadaOverviewFromWikipedia.docx
- HealthCanadaOverviewFromWikipedia.pptx
- SampleReport.docx
- SampleReport.pptx

**Comment by benjaminLuoHC** [comment]
Patched in PR #124
