### ISSUE TITLE
Import file-processing-tools library into other projects

### ISSUE THREAD

**Issue by benjaminLuoHC** [hc-sc-ocdo-bdpd/file-processing-tools#125]
The objective is for this file-processing-tools repo is to be a library that other projects can import and use. However, there are issues with relative imports and missing setup/initialization files which causes the system to throw errors

These errors should be resolved and a set of tests should be written to validate the functionality 

Edit: If possible, make the library installable through pip install

**Comment by pgaviganHC** [comment]
Redundant of other issues.
