### ISSUE TITLE
Code to determine file ownership is Windows-exclusive

### ISSUE THREAD

**Issue by benjaminLuoHC** [hc-sc-ocdo-bdpd/file-processing-tools#129]
The current implementation requires `pywin32`, which is a Windows-exclusive library that allows Python to communicate with Windows applications. The support should be extended to `MacOS` and `Linux` in the `file_processing/file_processor_strategy.py` file

**Comment by benjaminLuoHC** [comment]
The `import win32security` is now moved inside the conditional that checks whether the operating system is Windows (`win32`), but `pywin32` remains a dependency inside `requirements.txt`. We have to somehow indicate optional dependencies

While I was looking into publishing the library, I noticed that `pyproject.toml` and `setup.py` have support for optional dependencies so the end-users might not be directly installing from `requirements.txt` depending on how we choose to build the project

**Comment by benjaminLuoHC** [comment]
Can confirm `pywin32` being in `requirements.txt` is an issue - it causes the installation to fail on MacOS

**Comment by pgaviganHC** [comment]
This issue can also cause it to fail in online environments, such sa MS Fabric.

**Comment by benjaminLuoHC** [comment]
> This issue can also cause it to fail in online environments, such as MS Fabric.

Added check to circumvent this 

```py
    def _find_owner(self, file_path: str) -> str:
        if sys.platform == 'win32' and importlib.util.find_spec('pywin32'):
            import win32security
            sd = win32security.GetFileSecurity(file_path, win32security.OWNER_SECURITY_INFORMATION)
            owner_sid = sd.GetSecurityDescriptorOwner()
            name, domain, _ = win32security.LookupAccountSid(None, owner_sid)
            return f'{domain}/{name}'

        return ''
```

Now `pywin32` is only run when it's installed (as opposed to before, when the only requirement was having a Windows computer)

**Comment by BrennanHCSC** [comment]
Windows-specific dependency has been made optional.
