### ISSUE TITLE
Directory metadata analysis progress bar

### ISSUE THREAD

**Issue by benjaminLuoHC** [hc-sc-ocdo-bdpd/file-processing-tools#134]
Since the runtime of the directory analysis tool is rather long, the hope is to have a progress bar to estimate how long the program will run for

This is currently implemented in `directory.py` as a function of the total number of files. This is an accurate measure because the program processes files in tandem and each file takes approximately the same amount of time to process

However, it is time-consuming to count the number of files in a directory, especially for one on the scale of terabytes. Therefore, it is necessary to somehow estimate the total number of files

I have tested various Python libraries as well as cmd scripts. The current `os.walk` implementation is already very efficient and the only improvement I observed was from the `robocopy` cmd command which is roughly 20% faster (but still infeasible for larger directories)

It may be possible to run the program for a bit, track runtime v. data (in terms of file size) processed, then run a linear regression or curve fit to estimate total runtime after `n` files are processed, but this may lack accuracy due to runtime being a function of # of files rather than file size

**Comment by pgaviganHC** [comment]
May not be possible to address this issue. Perhaps revisit in the future if new use cases arrise.
