### ISSUE TITLE
Accessing library from MS Fabric

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#148]
Attempted to clone the repos into a notebook in MS Fabric using: `!pip install git+https://github.com/hc-sc-ocdo-bdpd/file-processing-tools.git`

The following is the error output:

> Collecting git+https://github.com/hc-sc-ocdo-bdpd/file-processing-tools.git
>   Cloning https://github.com/hc-sc-ocdo-bdpd/file-processing-tools.git to /tmp/pip-req-build-se93vztu
>   Running command git clone --filter=blob:none --quiet https://github.com/hc-sc-ocdo-bdpd/file-processing-tools.git /tmp/pip-req-build-se93vztu
>   Resolved https://github.com/hc-sc-ocdo-bdpd/file-processing-tools.git to commit d5ea2f23640531795d43eb7e1c6e9f361036ea0a
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [14 lines of output]
>       error: Multiple top-level packages discovered in a flat-layout: ['similarity', 'file_processing'].
>       
>       To avoid accidental inclusion of unwanted files or directories,
>       setuptools will not proceed with this build.
>       
>       If you are trying to create a single distribution with multiple packages
>       on purpose, you should not rely on automatic discovery.
>       Instead, consider the following options:
>       
>       1. set up custom discovery (`find` directive with `include` or `exclude`)
>       2. use a `src-layout`
>       3. explicitly set `py_modules` or `packages` with a list of names
>       
>       To find more information, look for "package discovery" on setuptools docs.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by benjaminLuoHC** [comment]
It seems that it's caused by the file structure

| file_processing
| similarity
| ...

There should only be one `src` directory. I moved `similarity` into `file_processing` and will test

**Comment by benjaminLuoHC** [comment]
Can you try again with this? I ran this locally in an empty folder and it took about 5.5 minutes

`%pip install git+https://github.com/hc-sc-ocdo-bdpd/file-processing-tools.git@similarity`

It's part of PR #149

**Comment by pgaviganHC** [comment]
Looks like this issue is resolved.
