### ISSUE TITLE
About - Optional dependences - Comments

### ISSUE THREAD

**Issue by charliekemp** [hc-sc-ocdo-bdpd/file-processing-tools#154]
Here are some comments that hopefully make these instructions related to optional requirements a bit easier to follow. In particular, the reference to future commands. Maybe put a sub-title such as Future Installation Method on this section so the readers do not have to read the text to understand the pypi option is not relevant, not the install_file_process to the installation at hand. Some suggested text: 

To enable file owner information extraction on Windows, you may need to install pywin32. This is an optional step but is recommended  to enhanced the functionality of the file process library. If it is already installed on your system it will be detected and a message will indicate the requirements are already satisfied. Use the following command install pywin32:
pip install pywin32

Installing Optional Developer Dependencies:

The file processing library includes optional developer dependencies specified in the pyproject.toml file. Currently, these dependencies cannot be installed directly from GitHub. (To be addressed in a future update, see Future Installation Method below) 

To install these optional dependencies, you will need to manually execute pip install <library_name> command  for each library listed under the developer dependencies section in pyproject.toml. (I am assuming this is correct) 

Future Installation Method Once Published on PyPI:

After the project is published on the Python Package Index (PyPI), you will be able to install all optional developer dependencies with a single command. This command will be:

pip install file_procesing_tools[developer]

**Comment by benjaminLuoHC** [comment]
Thanks for the overview - I've made changes and re-published the documentation
