### ISSUE TITLE
About - Getting Started - Comments

### ISSUE THREAD

**Issue by charliekemp** [hc-sc-ocdo-bdpd/file-processing-tools#155]
I feel it may be better to err on the side of plain language for the About text on this project. The following text is not 100% complete. I need to play with the code a little more. Take this a suggestions as to how we might make this less technical. 

Getting started
To start using the file processing library, you'll need to set up two parts: the "File" component and the "Directory” component. These as two different toolboxes, each having their own features, functionality and uses. To make these toolboxes ready for use you need to "initialize" them.

File Component: This is like a toolbox for working with individual files. Once set up, it allows you to perform tasks on that single files, such as opening and  getting information about the file.

Directory Component: This is  a toolbox for managing folders on a file system. Setting up this component lets you work with groups of files/folders – such as collecting metadata on all the files at once.
. Initializing simply means getting them ready to perform their tasks. Once they're set up, you can start accessing all the tools and features each component offers.

Working with Individual Files:
To process individual files you the “File” component needs to set-up”. Here’s how: 

from file_processing import File
file = File('path/to/your/file')

Once you have set-up the “File” component you can easily get information about it, like when it was last the file was accessed, with a simple command:

file.access_time

You can also get a complete list of all the file's details in one go. 

metadata = file.processor.__dict__

Note: Note that the key names will vary as each file type may have its own metadata, as defined in the Introduction

Comparing two files for similarity: 
To find out how similar two files are to one another, you first set up the file components as described above. Then, you can compare them using either Cosine Similarity or Levenshtein Distance methods:
<Cosine similarity and Levenstein Distance examples> 

Working with Directories (Folders):

Setting up for a folder: 
To work with all the files in a folder, you set up a 'Directory' component, described above This lets you collect information on all the files:
from file_processing import Directory
directory = Directory('path/to/your/folder')

Creating Reports: 
(I need to have a closer look at the reporting before suggesting changes here) 
Metadata Reports:
Analytics Report:

Finding Similar Files in a Directory
You can find files that are similar to each other within a directory by using either cosine similarity or a more advanced method like FAISS indices. This helps in identifying duplicates and closely related files.
Use the identify_duplicates() class method to create a CSV that compares file similarities. There are 2 configurations for this:
Use cosine similarity to compare every file against each other
Use FAISS indicies to return to return the top_n most similar files
<examples>

**Comment by benjaminLuoHC** [comment]
Thank you for this - in hindsight I agree it's too technical despite my initial attempts at simplicity

I cut out a great deal of the technical terms but suspect installation will be tricky. I might create short ~5-15 second videos and embed them into the documentation if this would help

**Comment by charliekemp** [comment]
Reviewed updated documentation.
