### ISSUE TITLE
Metadata Report Error - Object of type IndirectObject is not JSON serializable

### ISSUE THREAD

**Issue by charliekemp** [hc-sc-ocdo-bdpd/file-processing-tools#157]
Was able to duplicate this error on two different systems. In both cases the same error occurred while trying to generate a metadata report for a directory. In both cases the processing to the files completes and the error occurs during the generation of the metadata report: TypeError: Object of type IndirectObject is not JSON serializable. In one case I am running the directory processing on my OneDrive and the other instance on a different computer runing on the downloads folder which has a variety of filetype. 
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 directory.generate_report('C:/Users/CKEMP/OneDrive - HC-SC PHAC-ASPC/metadata_report.csv')

File c:\Users\...\OneDrive - HC-SC PHAC-ASPC\Documents\GitHub\IDP\file-processing-tools\file_processing\directory.py:227, in Directory.generate_report(self, report_file, include_text, filters, keywords, check_title_keywords, migrate_filters, open_files, split_metadata, char_limit)
    224 df.columns = df.columns.str.replace('keywords_', 'Text.')
    226 if not split_metadata:
--> 227     df['metadata'] = df['metadata'].apply(json.dumps)
    229 # Converting booleans to integers (True->1; False->0)
    230 for boolean in ['is_file', 'is_symlink']:

File c:\Users\...\OneDrive - HC-SC PHAC-ASPC\Documents\GitHub\IDP\file-processing-tools\.venv\lib\site-packages\pandas\core\series.py:4904, in Series.apply(self, func, convert_dtype, args, by_row, **kwargs)
   4769 def apply(
   4770     self,
   4771     func: AggFuncType,
   (...)
   4776     **kwargs,
   4777 ) -> DataFrame | Series:
   4778     """
   4779     Invoke function on values of Series.
   4780 
   (...)
   4895     dtype: float64
   4896     """
   4897     return SeriesApply(
   4898         self,
   4899         func,
   4900         convert_dtype=convert_dtype,
   4901         by_row=by_row,
   4902         args=args,
   4903         kwargs=kwargs,
-> 4904     ).apply()

File c:\Users\...\OneDrive - HC-SC PHAC-ASPC\Documents\GitHub\IDP\file-processing-tools\.venv\lib\site-packages\pandas\core\apply.py:1427, in SeriesApply.apply(self)
   1424     return self.apply_compat()
   1426 # self.func is Callable
-> 1427 return self.apply_standard()

File c:\Users\...\OneDrive - HC-SC PHAC-ASPC\Documents\GitHub\IDP\file-processing-tools\.venv\lib\site-packages\pandas\core\apply.py:1507, in SeriesApply.apply_standard(self)
   1501 # row-wise access
   1502 # apply doesn't have a `na_action` keyword and for backward compat reasons
   1503 # we need to give `na_action="ignore"` for categorical data.
   1504 # TODO: remove the `na_action="ignore"` when that default has been changed in
   1505 #  Categorical (GH51645).
   1506 action = "ignore" if isinstance(obj.dtype, CategoricalDtype) else None
-> 1507 mapped = obj._map_values(
   1508     mapper=curried, na_action=action, convert=self.convert_dtype
   1509 )
   1511 if len(mapped) and isinstance(mapped[0], ABCSeries):
   1512     # GH#43986 Need to do list(mapped) in order to get treated as nested
   1513     #  See also GH#25959 regarding EA support
   1514     return obj._constructor_expanddim(list(mapped), index=obj.index)

File c:\Users\CKEMP\OneDrive - HC-SC PHAC-ASPC\Documents\GitHub\IDP\file-processing-tools\.venv\lib\site-packages\pandas\core\base.py:921, in IndexOpsMixin._map_values(self, mapper, na_action, convert)
    918 if isinstance(arr, ExtensionArray):
    919     return arr.map(mapper, na_action=na_action)
--> 921 return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)

File c:\Users\...\OneDrive - HC-SC PHAC-ASPC\Documents\GitHub\IDP\file-processing-tools\.venv\lib\site-packages\pandas\core\algorithms.py:1743, in map_array(arr, mapper, na_action, convert)
   1741 values = arr.astype(object, copy=False)
   1742 if na_action is None:
-> 1743     return lib.map_infer(values, mapper, convert=convert)
   1744 else:
   1745     return lib.map_infer_mask(
   1746         values, mapper, mask=isna(values).view(np.uint8), convert=convert
   1747     )

File lib.pyx:2972, in pandas._libs.lib.map_infer()

File C:\Program Files\Python310\lib\json\__init__.py:231, in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    226 # cached encoder
    227 if (not skipkeys and ensure_ascii and
    228     check_circular and allow_nan and
    229     cls is None and indent is None and separators is None and
    230     default is None and not sort_keys and not kw):
--> 231     return _default_encoder.encode(obj)
    232 if cls is None:
    233     cls = JSONEncoder

File C:\Program Files\Python310\lib\json\encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)

File C:\Program Files\Python310\lib\json\encoder.py:257, in JSONEncoder.iterencode(self, o, _one_shot)
    252 else:
    253     _iterencode = _make_iterencode(
    254         markers, self.default, _encoder, self.indent, floatstr,
    255         self.key_separator, self.item_separator, self.sort_keys,
    256         self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)

File C:\Program Files\Python310\lib\json\encoder.py:179, in JSONEncoder.default(self, o)
    160 def default(self, o):
    161     """Implement this method in a subclass such that it returns
    162     a serializable object for ``o``, or calls the base implementation
    163     (to raise a ``TypeError``).
   (...)
    177 
    178     """
--> 179     raise TypeError(f'Object of type {o.__class__.__name__} '
    180                     f'is not JSON serializable')

TypeError: Object of type IndirectObject is not JSON serializable

**Comment by benjaminLuoHC** [comment]
Patched, PR#161
