### ISSUE TITLE
Path to test files

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#169]
When running the test cases in PyCharm the tests all fail. This is because the tests all run from the "tests" directory, but the test cases alll have paths from the project root directory.

I have found that updating the test path to start with "./resources/..." instead of "test/resources/..." resolves this issue in PyCharm. However, I am concerned that doing this will break the CI/CD tests and the test runner in VS Code.

We therefore need to look to see what we can do to make the tests more generic. Is there a way to speficiy the location of all tests files so that this isn't an issue?

**Comment by BrennanHCSC** [comment]
Can likely use os or pathlib to create the absolute paths before all tests

**Comment by slamHC** [comment]
I'm not sure if this is what you are looking for but another solution/hack is to change the working directory for the tests to the project root directory. In Pycharm you can change the working directory of the test configuration to the project root directory with Run> Edit Configurations. You can also modify GitHub Actions in the CI.yml file to specify the working directory for the tests during runtime.

**Comment by pgaviganHC** [comment]
> I'm not sure if this is what you are looking for but another solution/hack is to change the working directory for the tests to the project root directory. In Pycharm you can change the working directory of the test configuration to the project root directory with Run> Edit Configurations. You can also modify GitHub Actions in the CI.yml file to specify the working directory for the tests during runtime.

Looks like a workable solution. Let's do a PR where we document this on the README and confirm that we can all get it to work.
