### ISSUE TITLE
Table columns stuck on 5

### ISSUE THREAD

**Issue by fnwaohaHC** [hc-sc-ocdo-bdpd/file-processing-tools#29]
The generated tables are stuck on 5 right now due to how the random data is generated.  A quick example on how the dataframe is generated using the pydbgen module: 

testdf=myDB.gen_dataframe(
25,fields=['name','city','phone',
'license_plate','email'],
real_email=True,phone_simple=True
)

The fields atrribute is what creates the columns. And pydbgen has multiple selections for the field attribute:
- Name, country, city, real (US) cities, US state, zipcode, latitude, longitude,
- Month, weekday, year, time, date, Personal email, official email, SSN
- Company, Job title, phone number, license plate

A solution to this is adding all these choices into a list and randomizing the number of row selections from this list to create the dataframe

**Comment by pgaviganHC** [comment]
Is this meaning to say that the artificial tables are locked to 5 columns?

**Comment by fnwaohaHC** [comment]
No it isnt locked. The fields attribute can take a list longer than 5 elements

**Comment by pgaviganHC** [comment]
> 

Can you please clarify what is "stuck on 5"? If it is not the number of columns I do not understand this issue.

**Comment by fnwaohaHC** [comment]
Okay, 'stuck' may be the wrong word. The columns aren't stuck on 5 but they are not dynamic. They don't change based on the column parameter for the object
