### ISSUE TITLE
Adding additional comments to code

### ISSUE THREAD

**Issue by charliekemp** [hc-sc-ocdo-bdpd/file-processing-tools#30]
Code looks great. However we should add comments to this code to make it easier to read, as well as enhancing the maintainability and collaborative/re-use  potential. This particularly important when the code/model required a significant amount of tweaking to in increase accuracy of the output and to capture the rationale behind modifications or improvements while we still remember the details.

**Comment by pgaviganHC** [comment]
Add comment blocks to each method describing inputs and expected outputs as well as comment blocks describing the purpose of each module and class.

**Comment by Louis-Boulet-HC** [comment]
Went through all the code I wrote in the project and added documentation throughout.
Will be merged through PR #70
