### ISSUE TITLE
test_extract_table_content Fails

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#31]
The test_extract_table_content test fails.

**Comment by Louis-Boulet-HC** [comment]
PR has just been submitted which should fix this, assertions have also been made more lenient to reflect high variability of the later metrics and them being somewhat dependent on the performance of the earlier ones

**Comment by Louis-Boulet-HC** [comment]
Fixed in most recent PR
