### ISSUE TITLE
OCR adds straight line characters to cells

### ISSUE THREAD

**Issue by Louis-Boulet-HC** [hc-sc-ocdo-bdpd/file-processing-tools#33]
Interprets column lines/separators as characters:  "|"
Possible causes include faulty OCR or imperfect cropping.
Will look into it soon and already have some sort of idea for the fix (likely a temporary one though).

**Comment by pgaviganHC** [comment]
I suspect that these | characters show up only at the beginning and end of the cell contents string. Perhaps str.replace("|","") will handle this for now.

Fine tuning of the bounding boxes may also help deal with this in the long run.
