### ISSUE TITLE
External Dependencies

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#4]
This project currently has an external dependency (Tesseract). This needs to be installed on the local machine in order to work properly.

This is not ideal as this install is seperate from the build process.

Containerization may enable the build process to include Tesseract as a dependency in the container, as opposed to a seperate install on the machine.

**Comment by benjaminLuoHC** [comment]
EasyOCR has been recommended to us by Microsoft for use in MS Fabric (the current Tesseract implementation cannot be installed in the MS Fabric environment)

Need to do a security check on EasyOCR
