### ISSUE TITLE
Packaging for Delivery

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#41]
The table extraction project needs to be "compiled" into a stand alone executable which can be run without needing to have a development environment.

**Comment by pgaviganHC** [comment]
I suspect that this is the solution: https://stackoverflow.com/questions/5458048/how-can-i-make-a-python-script-standalone-executable-to-run-without-any-dependen

**Comment by erikafung20** [comment]
Currently troubleshooting pyinstaller in the to_exe branch. Current error is the package timm is not found - which appears after the user enters a PDF file path as input to the exe

**Comment by pgaviganHC** [comment]
Looks like you are farther along that I am. I just tried it on my own branch and am having trouble getting pyinstaller to be found in the environment.

When this gets figured I think it will be a necessary to add documentation to he readme to explain how to build the exe.

**Comment by pgaviganHC** [comment]
Resolved by #69. Will open a new issue for teh GUI exe.
