### ISSUE TITLE
OneDrive API Access

### ISSUE THREAD

**Issue by pgaviganHC** [hc-sc-ocdo-bdpd/file-processing-tools#5]
Add functionality to use an api key to access files on OneDrive

**Comment by kmccloy-hc** [comment]
Investigating this. To confirm my understanding, the intent of this US is to be able to stream files from the OneDrive Graph storage API (includes SharePoint) in to `Document`?

**Comment by kmccloy-hc** [comment]
It appears that we do not have the Azure AD permissions to create new API keys

**Comment by pgaviganHC** [comment]
Stale, closing.
