### ISSUE TITLE
GUI exe not outputting intermediate steps

### ISSUE THREAD

**Issue by fnwaohaHC** [hc-sc-ocdo-bdpd/file-processing-tools#77]
The exe runs and outputs an excel file but the intermediate steps are not being outputted. Before the intermediate steps were working but it was missing additional files because the build_gui branch was behind on commits, so a new branch was made off that and rebased from main. 

In the new changes on main more intermediate steps were added and the function (process_content) return changed to a tuple. So a rebase was needed.

In the branch gui_intermediate-steps, within the GUI2, I changed line 67 to reflect the changes of that function. But now no intermediate steps are being outputted

**Comment by erikafung20** [comment]
Solved with #78
