### ISSUE TITLE
Handle corrupted and locked files

### ISSUE THREAD

**Issue by BrennanHCSC** [hc-sc-ocdo-bdpd/file-processing-tools#91]
Add functionality as described by title

**Comment by benjaminLuoHC** [comment]
The `directory.py` method now contains a `try... except` check to store the error in the file's metadata field and continue processing the remaining files

**Comment by pgaviganHC** [comment]
> The `directory.py` method now contains a `try... except` check to store the error in the file's metadata field and continue processing the remaining files

Based on this, can this issue be closed or does it require additional functionality? @BrennanHCSC

**Comment by benjaminLuoHC** [comment]
Added in PR #150
