### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by BrennanHCSC** [hc-sc-ocdo-bdpd/file-processing-tools#98]
- Delete SRC dir
- New repo for table extraction
- Remove redundancies in each (ex. requirements), make sure they work independently
- Add util for Table Extraction (Good student task?)
- Add demo services to show executable services
- Organize GUIs in table processing
 
- Once we have docker...dockerize both libs

**Comment by pgaviganHC** [comment]
This is mostly done. Will make a new issue for docker.
